### ISSUE TITLE
Auto detect iOS SDK version

### ISSUE THREAD

**Issue by lorenzoPrimi** [bassosimone/libight-build-ios#3]
It would be optimal to auto detect the user's iOS SDK version automatically and not have to update build_arch.sh manually every time.

**Comment by bassosimone** [comment]
Ok. I've started to look into this and I've seen that the output of `xcodebuild -showsdks` could be parsed to find the latest version of the iphoneos SDK, as described for example [here](http://stackoverflow.com/questions/4314804/parameter-for-xcodebuild-for-using-latest-sdk) and [here](http://stackoverflow.com/questions/26040040/parsing-xcodebuild-showsdks-for-build-script).

**Comment by AntonioLangiu** [comment]
This can be a solution 
https://github.com/ursachec/CPAProxy/blob/master/scripts/build-all.sh#L13

I think we need to update the build scripts.

**Comment by AntonioLangiu** [comment]
It should be fixed with [this](https://github.com/measurement-kit/measurement-kit/commit/022155f34d102363f4575298d5daedc3d3ba1102) commit on measurement-kit repo.
